baseurl = "https://adrianabreu.github.io"
languageCode = "es-ES"
title = "Adrián Abreu"
theme = "hugo-sustain"
Paginate = 8
Copyright = "2017 Adrián Abreu"

[params.social]
  Twitter = "aabreuglez"
  Github = "adrianabreu"
  Linkedin = "AdrianAbreu"
  Email = "me@adrianabreu.com"
 
 [permalinks]
  post = "/:year/:month/:day/:slug"

## Main Menu
[[menu.main]]
  name = "Inicio"
  weight = 100
  identifier = 1
  url = "/"
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = 2
  url = "/blog/"
[[menu.main]]
  name = "knowledge"
  identifier = 3
  weight = 200
  url = "/knowledge/"
[[menu.main]]
  name = "archive"
  weight = 100
  identifier = 4
  url = "/archive/"